# Generated by Django 3.2.8 on 2021-10-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя контакта')),
                ('city', models.CharField(max_length=128, verbose_name='название города')),
                ('phone', models.CharField(max_length=60, verbose_name='телефон')),
                ('email', models.CharField(max_length=60, verbose_name='электронная почта')),
                ('address', models.CharField(max_length=128, verbose_name='адрес')),
            ],
        ),
    ]
